export const prodotti = [
  {
    nome: 'T-shirt', prezzo: 25, descrizione: 'Una maglietta colorata', valutazione: 5, stagione: 'Invernale', link: 'assets/prodottiImg/tshirt.jpeg', taglie: [ 'XS', 'S', 'M', 'L', 'XL'], origine: 'China',
    descrlunga: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu lacinia lorem. Nunc vel placerat felis, ac dapibus elit. Quisque tristique quis turpis sit amet porta. Sed vel viverra tortor, hendrerit volutpat arcu. Duis porta neque eget nulla mattis molestie. Nam eleifend finibus quam et semper. Donec iaculis elit id nisi vehicula auctor consectetur a ante. Nam ut ex eu purus consequat mattis. Donec magna massa, vehicula a arcu non, ullamcorper semper nulla.\n' +
                'Sed ullamcorper, odio ut posuere bibendum, ex quam laoreet dolor, at rhoncus dolor purus ac purus. Proin cursus vel metus et efficitur. Suspendisse consectetur, ligula nec euismod ultricies, magna velit ultricies turpis, sit amet euismod sem arcu a erat. Suspendisse cursus massa ac lobortis dignissim. Curabitur maximus faucibus magna a congue. Vestibulum metus lacus, venenatis nec velit ut, bibendum rutrum libero. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et erat gravida, viverra magna vel, vulputate odio. Vivamus aliquet, leo a tristique consectetur, dolor orci ornare tortor, non porttitor urna magna hendrerit urna. Nullam et mi vestibulum, dignissim dui nec, semper ante. Maecenas vitae velit eget nulla pharetra condimentum id et lacus. Quisque lectus neque, congue ac commodo sit amet, fermentum nec tortor.\n' +
                'Morbi gravida ante non sollicitudin pretium. Aliquam luctus felis nec ex suscipit ultrices. Vestibulum consequat orci ullamcorper, maximus erat in, vulputate ipsum. Sed at arcu velit. Quisque eu semper turpis. Cras eleifend at ex id volutpat. Sed posuere condimentum tincidunt. Praesent bibendum risus arcu, at semper erat volutpat eget. Integer felis diam, tincidunt at ornare sit amet, sodales at magna. In lobortis imperdiet tortor in cursus. '
  },
  {
    nome: 'Pantaloni', prezzo: 45, descrizione: 'Leggeri ed eleganti', valutazione: 4, stagione: 'Invernale', link: '/assets/prodottiImg/pantaloni.jpeg', taglie: [ 'XS', 'S', 'XL'], origine: 'Germania',
    descrlunga: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel pulvinar risus. Proin venenatis, sapien at porta feugiat, nibh nisl iaculis libero, a ullamcorper leo tellus ut augue. Cras diam purus, faucibus sit amet elementum id, venenatis at tortor. Vivamus massa felis, dapibus vel erat non, interdum posuere ex. Aliquam nec dui consectetur, pretium metus non, maximus metus. Aenean ornare eget arcu vel aliquam. Fusce lobortis, ante ut mollis pharetra, magna nisi scelerisque dui, vel egestas quam justo sed arcu. Pellentesque ornare quis felis iaculis condimentum. Maecenas id accumsan dolor, eget posuere felis. Nam et pulvinar justo, eget feugiat tortor. Sed dapibus neque id molestie malesuada. Cras tincidunt, nisl ac euismod commodo, enim nulla facilisis mauris, nec feugiat dui urna non mauris. Proin auctor ex at nunc imperdiet ultrices.\n' +
                'Aliquam ut odio bibendum, luctus orci aliquam, lobortis justo. Nam vitae porta odio. Proin elit diam, facilisis quis enim nec, tempus tristique purus. Curabitur in est faucibus, congue ligula eget, tempor risus. In quis lectus sit amet tellus aliquam lobortis. Nunc egestas sodales risus, at maximus purus rutrum a. Proin nec ornare augue. Curabitur lobortis ipsum vitae mauris consequat, ac fermentum lectus gravida.\n' +
                'Suspendisse potenti. Ut lacinia, sem at interdum ultricies, odio orci feugiat tortor, at iaculis nunc turpis eget justo. Ut sit amet diam in ipsum posuere pellentesque. Fusce elit velit, ultrices id tortor cursus, pharetra molestie quam. Morbi eu efficitur lorem. Nulla lobortis feugiat tortor, sit amet pretium mi placerat at. Morbi eget eros at ante faucibus gravida sed nec orci. Etiam porttitor varius nisl eget venenatis. Cras malesuada mollis ligula et tristique. Nulla ut commodo lacus. Donec non enim vel arcu dictum dapibus a nec eros. Aenean placerat ex nulla, tempor consequat quam iaculis sed. '
  },
  {
    nome: 'Felpa', prezzo: 35, descrizione: 'Morbido per i climi freddi', valutazione: 5, stagione: 'Invernale', link: '/assets/prodottiImg/felpa.jpeg', taglie: [ 'M', 'L', 'XL'], origine: 'Stati Uniti',
    descrlunga: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent aliquam augue erat, eget venenatis sapien consectetur nec. Phasellus scelerisque libero at metus pretium, fermentum vehicula erat aliquam. Aliquam erat volutpat. Etiam imperdiet, augue non auctor sagittis, nisl diam rutrum ligula, nec semper nunc nunc sollicitudin purus. Morbi et placerat odio, ut iaculis elit. Fusce ut pulvinar augue, sit amet accumsan nunc. Morbi porta felis ut est malesuada condimentum.\n' +
                'Nulla eget justo at enim feugiat semper eget nec nibh. Vestibulum ac enim eu neque vulputate fermentum sit amet et ex. Proin consectetur sapien vel pretium gravida. Sed sit amet turpis magna. Ut velit ante, fermentum et ex id, mattis imperdiet urna. Vivamus sit amet nulla aliquet, suscipit erat sagittis, venenatis est. Nulla non arcu sed urna gravida luctus. Nunc facilisis dignissim purus, sit amet finibus mi faucibus eget. Integer dignissim ligula mauris, ut vestibulum felis ultricies ac.\n' +
                'Sed nibh dui, posuere vitae turpis ut, tincidunt efficitur urna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In dignissim augue ac nibh iaculis, id posuere libero commodo. Donec auctor tincidunt tempus. Aenean fringilla nisl ac congue mollis. Nam efficitur dolor nec posuere vehicula. Ut eget molestie velit. Vivamus sagittis, lectus quis lobortis feugiat, tortor justo porta mauris, ac iaculis odio velit ac dui. Praesent maximus, lorem sit amet molestie dapibus, justo quam facilisis orci, semper posuere urna lectus sit amet diam. Quisque sed facilisis eros. '
  },
  {
    nome: 'Cintura', prezzo: 60, descrizione: 'In pura ecopelle', valutazione: 3, stagione: 'Neutro', link: '/assets/prodottiImg/cintura.jpeg', taglie: [ 'XS', 'S', 'L', 'XL'], origine: 'Italia',
    descrlunga: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a nisl mollis, fringilla purus id, ultrices sem. Donec vel pharetra nunc. Sed vitae lectus efficitur mauris vehicula blandit ac eget nisi. Nunc ut ipsum sit amet sem vestibulum gravida. Nunc faucibus ac sapien id viverra. Nulla facilisi. Phasellus id sapien magna. Ut sit amet sapien suscipit, elementum lacus et, aliquet est. Nunc mollis, orci non lacinia malesuada, diam nisi eleifend libero, vel gravida velit arcu a arcu. Curabitur vitae pharetra felis, sed mattis tellus.\n' +
                'Nam vitae hendrerit tellus. Ut nec magna condimentum, pulvinar augue eu, tempus nibh. Quisque faucibus odio vel ipsum accumsan, at suscipit justo sagittis. Quisque vel dolor in ipsum dignissim consequat. Sed convallis rhoncus velit blandit ultrices. Nam facilisis molestie tempus. Maecenas consectetur non ipsum at egestas. Sed auctor purus at mauris pretium pulvinar. Suspendisse id lacinia diam. Maecenas sit amet gravida magna, tincidunt volutpat erat. Nunc a dui metus. In eu massa sit amet nulla auctor laoreet. Donec ut sagittis orci. Nulla quis sem felis. Pellentesque condimentum accumsan nulla, in molestie est aliquam hendrerit. Proin vulputate purus in neque porta, in placerat nisi varius.\n' +
                'Ut gravida orci id venenatis lacinia. Aliquam iaculis velit sed elit consequat, et fringilla turpis pretium. Nulla porttitor quis odio et commodo. Aliquam commodo nunc non euismod mollis. Mauris consequat quam ut turpis dignissim sollicitudin. Vestibulum accumsan mattis quam at pulvinar. Sed eget sagittis ex. Integer sed fermentum felis. Quisque euismod purus sit amet porta dapibus. Sed feugiat ultricies odio. Aenean varius, turpis in ultricies eleifend, leo odio fermentum erat, quis pretium velit mi a enim. Quisque consectetur orci purus, porttitor congue augue consequat nec. Nunc ut metus quis nisi hendrerit porta. Fusce fringilla maximus leo, ac vehicula quam gravida vitae. Maecenas malesuada egestas erat blandit ultrices. Aenean sollicitudin rutrum quam at interdum. '
  },
  {
    nome: 'Mascherina', prezzo: 5, descrizione: 'Fp1 colorata', valutazione: 2, stagione: 'Neutro', link: '/assets/prodottiImg/mascherina.jpeg', taglie: [ 'Taglia Unica' ], origine: 'Vietnam',
    descrlunga: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a nisl mollis, fringilla purus id, ultrices sem. Donec vel pharetra nunc. Sed vitae lectus efficitur mauris vehicula blandit ac eget nisi. Nunc ut ipsum sit amet sem vestibulum gravida. Nunc faucibus ac sapien id viverra. Nulla facilisi. Phasellus id sapien magna. Ut sit amet sapien suscipit, elementum lacus et, aliquet est. Nunc mollis, orci non lacinia malesuada, diam nisi eleifend libero, vel gravida velit arcu a arcu. Curabitur vitae pharetra felis, sed mattis tellus.\n' +
                'Nam vitae hendrerit tellus. Ut nec magna condimentum, pulvinar augue eu, tempus nibh. Quisque faucibus odio vel ipsum accumsan, at suscipit justo sagittis. Quisque vel dolor in ipsum dignissim consequat. Sed convallis rhoncus velit blandit ultrices. Nam facilisis molestie tempus. Maecenas consectetur non ipsum at egestas. Sed auctor purus at mauris pretium pulvinar. Suspendisse id lacinia diam. Maecenas sit amet gravida magna, tincidunt volutpat erat. Nunc a dui metus. In eu massa sit amet nulla auctor laoreet. Donec ut sagittis orci. Nulla quis sem felis. Pellentesque condimentum accumsan nulla, in molestie est aliquam hendrerit. Proin vulputate purus in neque porta, in placerat nisi varius.\n' +
                'Ut gravida orci id venenatis lacinia. Aliquam iaculis velit sed elit consequat, et fringilla turpis pretium. Nulla porttitor quis odio et commodo. Aliquam commodo nunc non euismod mollis. Mauris consequat quam ut turpis dignissim sollicitudin. Vestibulum accumsan mattis quam at pulvinar. Sed eget sagittis ex. Integer sed fermentum felis. Quisque euismod purus sit amet porta dapibus. Sed feugiat ultricies odio. Aenean varius, turpis in ultricies eleifend, leo odio fermentum erat, quis pretium velit mi a enim. Quisque consectetur orci purus, porttitor congue augue consequat nec. Nunc ut metus quis nisi hendrerit porta. Fusce fringilla maximus leo, ac vehicula quam gravida vitae. Maecenas malesuada egestas erat blandit ultrices. Aenean sollicitudin rutrum quam at interdum. '
  },
  {
    nome: 'Scarpe', prezzo: 50, descrizione: 'Comode e rinforzate', valutazione: 5, stagione: 'Invernale', link: '/assets/prodottiImg/scarpe.jpeg', taglie: [ '38', '39', '40', '41', '42', '43', '45'], origine: 'Italia',
    descrlunga: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a nisl mollis, fringilla purus id, ultrices sem. Donec vel pharetra nunc. Sed vitae lectus efficitur mauris vehicula blandit ac eget nisi. Nunc ut ipsum sit amet sem vestibulum gravida. Nunc faucibus ac sapien id viverra. Nulla facilisi. Phasellus id sapien magna. Ut sit amet sapien suscipit, elementum lacus et, aliquet est. Nunc mollis, orci non lacinia malesuada, diam nisi eleifend libero, vel gravida velit arcu a arcu. Curabitur vitae pharetra felis, sed mattis tellus.\n' +
                'Nam vitae hendrerit tellus. Ut nec magna condimentum, pulvinar augue eu, tempus nibh. Quisque faucibus odio vel ipsum accumsan, at suscipit justo sagittis. Quisque vel dolor in ipsum dignissim consequat. Sed convallis rhoncus velit blandit ultrices. Nam facilisis molestie tempus. Maecenas consectetur non ipsum at egestas. Sed auctor purus at mauris pretium pulvinar. Suspendisse id lacinia diam. Maecenas sit amet gravida magna, tincidunt volutpat erat. Nunc a dui metus. In eu massa sit amet nulla auctor laoreet. Donec ut sagittis orci. Nulla quis sem felis. Pellentesque condimentum accumsan nulla, in molestie est aliquam hendrerit. Proin vulputate purus in neque porta, in placerat nisi varius.\n' +
                'Ut gravida orci id venenatis lacinia. Aliquam iaculis velit sed elit consequat, et fringilla turpis pretium. Nulla porttitor quis odio et commodo. Aliquam commodo nunc non euismod mollis. Mauris consequat quam ut turpis dignissim sollicitudin. Vestibulum accumsan mattis quam at pulvinar. Sed eget sagittis ex. Integer sed fermentum felis. Quisque euismod purus sit amet porta dapibus. Sed feugiat ultricies odio. Aenean varius, turpis in ultricies eleifend, leo odio fermentum erat, quis pretium velit mi a enim. Quisque consectetur orci purus, porttitor congue augue consequat nec. Nunc ut metus quis nisi hendrerit porta. Fusce fringilla maximus leo, ac vehicula quam gravida vitae. Maecenas malesuada egestas erat blandit ultrices. Aenean sollicitudin rutrum quam at interdum. '
  }
];
